FORMAT: 1A
HOST: https://altmetrics.apiblueprint.org/

# HIRMEOS Altmetrics

The HIRMEOS Altmetrics service collects metrics for books that it has URIs for.
Specifically, a single DOI, and one or more URLs. The Altmetrics API primarily
provides a means to register URIs for one or more books on the Altmetrics service.


## Token Endpoint [/api/get_token]

### Fetch a Token [GET]

Interacting with the Altmetrics service requires a token for authorisation.

This endpoint uses BasicAuth (username/password) to authenticate you as a 
user, and issues a token that can be used for posting URIs to the Altmetrics
service, as well as events to the Metics API. 

+ Request
    + Headers

            Authorization: Basic email:password

+ Response 200 (text/html)

        Wl2IEbI029Uj969wAIsUJdEZWI2nuiNeIGOGjmJyihsIIZiiiMW0sJdjxjQIGi3ihj17.mIGNiI7ISQIlNViCsGss0wh9JtUgiNhZsiIJuy1YNFQCkv24yuG2GIsIIFdY27iAWetSiG2diICI2lIir1kFcSvQJzIdNlIhIjblJ_o7e2Yis9RVCNs0rXsbWJ10tlNnEYFJs7IFL1yedL36PslJrAAISuv
        
 
### Fetch a Token [POST]

A POST endpoint was added as this is how other HIRMEOS services have requested
the fetch-token endpoint to work. 

The response format is also JSON, instead of text, and contains far more 
detailed token information.


+ Request
    + Headers

            Authorization: Basic email:password

+ Response 200 (application/json)

        {
          "status": "ok",
          "count": 1,
          "code": 200,
          "data": [
            {
              "surname": "rahtrehleigr",
              "name": "houan",
              "authority": "pleb",
              "token": "Wl2IEbI029Uj969wAIsUJdEZWI2nuiNeIGOGjmJyihsIIZiiiMW0sJdjxjQIGi3ihj17.mIGNiI7ISQIlNViCsGss0wh9JtUgiNhZsiIJuy1YNFQCkv24yuG2GIsIIFdY27iAWetSiG2diICI2lIir1kFcSvQJzIdNlIhIjblJ_o7e2Yis9RVCNs0rXsbWJ10tlNnEYFJs7IFL1yedL36PslJrAAISuv",
              "email": "h.rahtrehleigr@agreemail.com"
            }
          ]
        }


## URIs Endpoint [/api/uriset]

### Fetch URIs [GET]

Get all URIs associated with the your user account, authenticated with a token
using the Bearer schema.

+ Request
    + Headers

            Authorization: Bearer Wl2IEbI029Uj969wAIsUJdEZWI2nuiNeIGOGjmJyihsIIZiiiMW0sJdjxjQIGi3ihj17.mIGNiI7ISQIlNViCsGss0wh9JtUgiNhZsiIJuy1YNFQCkv24yuG2GIsIIFdY27iAWetSiG2diICI2lIir1kFcSvQJzIdNlIhIjblJ_o7e2Yis9RVCNs0rXsbWJ10tlNnEYFJs7IFL1yedL36PslJrAAISuv

+ Response 200 (application/json)

        {
          "data": [
            {
              "urls": [
                "https://www.ancient-asia-journal.com/articles/10.5334/aa.06102",
                "https://www.ancient-asia-journal.com/articles/10.5334/aa.06102/galley/4/download",
                "https://www.ancient-asia-journal.com/articles/10.5334/aa.06102/galley/3/download"
              ],
              "last_checked": null,
              "raw": "10.5334/aa.06102"
            },
            {
              "urls": [
                "https://www.ubiquitypress.com/site/books/10.5334/baj",
                "https://www.ubiquitypress.com/site/books/10.5334/baj/read",
                "https://www.ubiquitypress.com/site/books/10.5334/baj/download/1346",
                "https://www.ubiquitypress.com/site/books/10.5334/baj/download/1016",
                "https://www.ubiquitypress.com/site/books/10.5334/baj/download/1015"
              ],
              "last_checked": "2020-05-13T13:52:14.034245+00:00",
              "raw": "10.5334/baj"
            },
            {
                "... etc": "... etc"
            }
          ]
        }
        
### Register URIs [POST]

Register new URIs associated, authenticated with a token using the Bearer schema.

+ Request (application/json)
    + Headers

            Authorization: Bearer Wl2IEbI029Uj969wAIsUJdEZWI2nuiNeIGOGjmJyihsIIZiiiMW0sJdjxjQIGi3ihj17.mIGNiI7ISQIlNViCsGss0wh9JtUgiNhZsiIJuy1YNFQCkv24yuG2GIsIIFdY27iAWetSiG2diICI2lIir1kFcSvQJzIdNlIhIjblJ_o7e2Yis9RVCNs0rXsbWJ10tlNnEYFJs7IFL1yedL36PslJrAAISuv

    + Body
    
            [   
              {
                "doi": "10.5334/bam",
                "url": [
                  "https://www.ubiquitypress.com/site/books/10.5334/bam",
                  "https://www.ubiquitypress.com/site/books/10.5334/bam/read",
                  "https://www.ubiquitypress.com/site/books/10.5334/bam/download/1610",
                  "https://www.ubiquitypress.com/site/books/10.5334/bam/download/1611",
                  "https://www.ubiquitypress.com/site/books/10.5334/bam/download/1613"
                ]
              },
              {
                "doi": "10.5334/bay",
                "url": [
                  "https://www.ubiquitypress.com/site/books/10.5334/bay",
                  "https://www.ubiquitypress.com/site/books/10.5334/bay/read",
                  "https://www.ubiquitypress.com/site/books/10.5334/bay/download/1888",
                  "https://www.ubiquitypress.com/site/books/10.5334/bay/download/1889",
                  "https://www.ubiquitypress.com/site/books/10.5334/bay/download/1891"
                ]
              }
            ]

+ Response 200 (application/json)

        '200'